### ISSUE TITLE
Explore Moving to Custom Elements v1

### ISSUE THREAD

**Issue by jsmecham** [jsmecham/atom-terminal-tab#51]
It doesn't look like Atom's view registry works well with the v1 spec for custom elements. We're stuck using the deprecated v0 specification for now. I'd like to investigate this further to see if it's something we can do and/or add support for in Atom.

**Comment by jsmecham** [comment]
The thing I can't figure out is how to export something that the view registry can use. `document.registerElement` returns such a constructor that is compatible, but using `window.customElements.define` returns `undefined` and returning the subclass of `HTMLElement` fails with the view registry.

**Comment by daviwil** [comment]
Just did a quick search on custom elements, looks like general support/usage has been deprecated:

- https://github.com/atom/atom/issues/3679#issuecomment-277726087
- https://github.com/atom/atom/issues/13254

I'll ask people on the team about it tomorrow to see if it's something to avoid

**Comment by jsmecham** [comment]
I remember reading about this, but the Flight Manual still makes recommendations to use custom elements. If this is not the case, its a disservice that it should still be making that recommendation if custom elements are doomed to lose support in Atom 2. I'd be happy to make a PR to remove that wording from the Flight Manual, if that is indeed the case.

For #47, I have (had) refactored the view as a subclass of `HTMLElement` in order to gain access to the `attachedCallback` (suggested on Slack by @BinaryMuse). I cannot attach the Xterm instance to the add-on's view until the view itself has been added to the DOM (see https://github.com/xtermjs/xterm.js/issues/1158), so the `attachedCallback` is an elegant way to manage this lifecycle. While this works great for now, I don't want to continue in this direction if it is deprecated.

I want to make Terminal Tab follow as closely as possible to the best practices of Atom, where it makes logical sense. If that means not using a custom element to help with snapshotting, that seems worth doing.

After moving away from a custom element, I will still need to know when my view is added to the DOM. I have not found a way to attach to any lifecycle events or callbacks that will inform my view that this has occurred. SIs there no current API for knowing when this occurs? Am I meant to implement my own `MutationObserver`?

**Comment by BinaryMuse** [comment]
Hey, @jsmecham! Just popping in since I was pinged in the above comment. :)

In general, we don't really recommend using custom elements these days. Sorry that my message in Slack wasn't very clear. This is mostly because custom elements live in a global namespace — they're not versionable nor do they have any real "scope" that allows two elements to share a name in different parts of the codebase (or even in completely unrelated packages). However, this is mostly a problem in core — a lot of our built-in UI widgets were built with custom elements, and they suffer from the aforementioned problems, as well as the fact that they don't play well with [snapshotting](http://blog.atom.io/2017/04/18/improving-startup-time.html). Deprecating them in core mostly affects packages because packages may need to change up their _usage_ of our custom elements if and when we remove them.

For your _own_ UI elements, you're really free to implement them however you want. The Atom view system will probably always support _displaying_ custom elements as a view, because they're just elements, and we want to support displaying plain elements (like `div`). Atom doesn't really prescribe too much how you implement things. That said, these days we're using a lot of [Etch](https://github.com/atom/etch), which is like a light version of React. That said, there's nothing built in to Etch that solves your problem of needing to know when an element has been attached to the DOM.

Hope this helps provide a little more light. 🔦

**Comment by jsmecham** [comment]
Thank you so much for the explanation and background, @BinaryMuse! Going to close this, since I do want to try and keep Terminal Tab following the patterns in Atom core as much as possible.
