### ISSUE TITLE
Close terminal shortcut

### ISSUE THREAD

**Issue by roccomuso** [jsmecham/atom-terminal-tab#76]
Any shortcut to close/hide the terminal?

thanks

**Comment by jsmecham** [comment]
You should be able to use the shortcut for closing an editor tab on your platform of choice. On macOS, `cmd-w` closes terminal tabs for me.

Depending on where you like to have your terminal tab instances displayed (i.e. bottom dock), you could add a keybinding to the `Window: Toggle Bottom Dock` command (or just launch that from the command palette).

Since there can be multiple terminals open throughout the Atom interface at any given time, there's not much sense in adding a specific shortcut to toggle its display like you can with say the tree view or git commit view, in my opinion.

**Comment by roccomuso** [comment]
@jsmecham That's the point. `Ctrl+W` doesn't work for me. I'm able to close regular tabs, but not the terminal tab.

**Comment by jsmecham** [comment]
Ah, you are likely being hit by the fact that Xterm swallows all the Ctrl key events. I'm working on an update that drastically improves key handling and fixes a lot of these issue. Stay tuned.
